# Install XFCE4 and Desktop Utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
    xfce4 \
    xfce4-terminal \
    xfce4-taskmanager \
    xfce4-screenshooter \
    xfce4-notifyd \
    xfce4-clipman-plugin \
    xfce4-whiskermenu-plugin \
    thunar-archive-plugin \
    dbus \
    dbus-x11 \
    x11-utils \
    x11-xserver-utils \
    x11-apps \
    xdotool \
    mesa-utils \
    fonts-noto-cjk \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
